// allReflectionFile.h, Generated by inja template engine.
// This file is used for supporting reflection, don't modify it !!
#pragma once
#include "../path/to/core/reflection.h"
#include "_generated/serializer/all_serializer.h"

// Auto-generated include files:
#include "Core\Reflection\Example\Animal.h"
#include "Core\Reflection\Example\Student.h"

namespace ZeroEngine::Reflection
{
    void TypeMetaRegister::MetaRegister()
    {
    // Auto-generated register functions
        TypeMetaRegister::Animal();
        TypeMetaRegister::Student();
    }
} // namespace ZeroEngine::Reflection
