// allReflectionFile.h, Generated by inja template engine.
// This file is used for supporting reflection, don't modify it !!
#pragma once

// Auto-generated include files:
#include "Animal.reflgen.h"
#include "Student.reflgen.h"

namespace ZeroEngine::Reflection::TypeMetaRegister
{
    static void DoMetaRegister()
    {
        // Auto-generated register functions
        TypeWrapperRegister::Register_Animal();
        TypeWrapperRegister::Register_Student();
    }
} // namespace ZeroEngine::Reflection
